config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'

  resources :movies do
    resources :reviews, except: [:show, :index]
    resources :ratings
    resources :favorite_movies, only: [:create, :destroy]
  end

  resources :reviews do
    resources :report_reviews, only: [:create, :destroy]
  end

  devise_for :users

  resources :users, only: [:show]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :movies, only: [:index, :show]
    end
  end
  get '/home' => 'pages#home'
  root 'pages#home'

end

app/views/shared/_leaving_site.html.erb
<div class='modal fade' id='leaving_account' tabindex='-1' role='dialog' aria-labelledby='myModalLabel'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class='modal-title' id='myModalLabel'>Leaving Movie Rated</h4>
      </div>
      <div class='modal-body'>
      <div class='row'>
        <div class='col col-sm-4 col-md-4 col-lg-4'>
          <%= image_tag 'alert.jpg', class: 'img-thumbnail' %>
        </div>
        <div class=' col col-sm-4 col-md-4 col-lg-4 '>
          <p>
            We regret to see you leaving!
            Are you sure you want to leave?
          </p>
          <%= button_to 'Cancel my account', registration_path(resource_name), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger btn-block' %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class='modal fade bs-example-modal-lg' id='search-modal' tabindex='-1' role='dialog' aria-labelledby='myLargeModalLabel'>
  <div class='modal-dialog modal-lg'>
    <div class='modal-content radius-none'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class='modal-title align-center '>Search Movies</h4>
      </div>

      <div class='container-fluid'>
        <%= form_tag movies_path, method: :get, class: 'form-horizontal' do %>
          <div class='row padding-top'>
            <%= text_field_tag name = 'search[text]', set_param_value(:text), class: 'form-control radius-none input-group-lg search-field', placeholder: 'Search Movies Here' %>
          </div>

          <div class='well radius-none margin-top-40'>
            <div class='row'>
              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>Genre</label>
                <%= select_tag name = 'search[genre]', options_for_select(collection_for_movie_genre, set_param_value(:genre)), include_blank: 'Please Select Genre', class: 'form-control radius-none' %>
              </div>

              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>Actors</label>
                <%= text_field_tag name = 'search[actor]', set_param_value(:actor), class: 'form-control radius-none', placeholder: 'Search Actor Here' %>
              </div>
            </div>

            <div class='row'>
              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>Start Date</label>
                <%= date_field_tag name = 'search[start_date]', set_param_value(:start_date), class: 'form-control radius-none', placeholder: 'Search By Start Date' %>
              </div>

              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>End Date</label>
                <%= date_field_tag name = 'search[end_date]', set_param_value(:end_date), class: 'form-control radius-none', placeholder: 'Search By End' %>
              </div>
            </div>
          </div>

          <div class='row '>
            <%= button_tag(type: 'submit', class: 'btn btn-primary btn-block btn-lg paddinng-top radius-none') do %>
              <span class='glyphicon glyphicon-search padding-right-10' aria-hidden='true'></span>Search
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>