config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'

  resources :movies do
    resources :reviews, except: [:show, :index]
    resources :ratings
    resources :favorite_movies, only: [:create, :destroy]
  end

  resources :reviews do
    resources :report_reviews, only: [:create, :destroy]
  end

  devise_for :users

  resources :users, only: [:show]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :movies, only: [:index, :show]
    end
  end
  get '/home' => 'pages#home'
  root 'pages#home'

end

app/views/layouts/_alert.html.erb
<div class='alert my-alert col col-md-4 col-lg-4 col-sm-4 col-lg-offset-4 ' id='custom_alert'>
  <div id='message'></div>
</div>

app/views/layouts/_footer.html.erb
<footer class='site-footer allign-center font-white'>
  <p>This is the demo footer</p>
</footer>

app/views/layouts/_header.html.erb
<div class='main-header'>
  <nav class='navbar navbar-default'>
    <div class='container-fluid'>
      <div class='navbar-header'>
        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar2'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        </button>
        <%= image_tag 'icon.png', class: 'img-thumbnail icon-pic' %>
      </div>
      <div id='navbar2' class='navbar-collapse collapse'>
        <ul class='nav navbar-nav navbar-right padding-top'>
          <% if user_signed_in? %>
            <li class='dropdown'>
              <%= link_to current_user.first_name, '#', class: 'dropdown-toggle', data: {toggle:'dropdown'} %>
              <ul class='dropdown-menu' role='menu'>
                <li>
                  <%= link_to 'Edit Profile', edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to 'View Profile', user_path(current_user) %>
                </li>
                <li class='divider'></li>
                <li>
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to 'Login', new_user_session_path, class: 'btn btn-default btn-lg' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>
<nav class='navbar navbar-inverse' data-spy='affix' data-offset-top='140'>
  <div class='container-fluid'>
    <div id='navbar2' class='navbar-collapse collapse'>
      <ul class='nav navbar-nav'>
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'Movies', movies_path %></li>
        <li>
          <%= link_to 'Advance Search', '#', 'data-toggle' => 'modal', 'data-target' => '#search-modal' %>
        </li>
        <li><%= render 'layouts/simple_search_form'%></li>
      </ul>
    </div>
  </div>
</nav>
<%= render 'layouts/search_form' %>

app/views/layouts/_search_form.html.erb
<div class='modal fade bs-example-modal-lg' id='search-modal' tabindex='-1' role='dialog' aria-labelledby='myLargeModalLabel'>
  <div class='modal-dialog modal-lg'>
    <div class='modal-content radius-none'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class='modal-title align-center '>Search Movies</h4>
      </div>

      <div class='container-fluid'>
        <%= form_tag movies_path, method: :get, class: 'form-horizontal' do %>
          <div class='row'>
            <div class='input-group input-group-lg'>
              <span class='input-group-addon  radius-none' id='basic-addon3'>Enter Key Words</span>
              <%= text_field_tag :search, params[:search], class:'form-control radius-none input-group-lg radius-none', placeholder: 'Search Movies Here', 'aria-describedby'=>'basic-addon3' %>
            </div>
          </div>

          <div class='well radius-none'>
            <div class='row padding-top'>
              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>Genre</label>
                <%= select_tag :genre, options_for_select(collection_for_movie_genre), include_blank: 'Please Select Genre', class: 'form-control radius-none' %>
              </div>

              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>Actors</label>
                <%= text_field_tag :actor, params[:actor], class:'form-control radius-none', placeholder: 'Search Actor Here' %>
              </div>
            </div>

            <div class='row'>
              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>Start Date</label>
                <%= date_field_tag :start_date, params[:start_date], class:'form-control radius-none', placeholder: 'Search By Start Date' %>
              </div>

              <div class='col col-lg-6 col-md-6 col-sm-6'>
                <label>End Date</label>
                <%= date_field_tag :end_date, params[:end_date], class:'form-control radius-none', placeholder: 'Search By End' %>
              </div>
            </div>
          </div>

          <div class='row '>
            <%= button_tag(type: 'submit', class: 'btn btn-primary btn-block paddinng-top radius-none') do %>
              <span class='glyphicon glyphicon-search' aria-hidden='true'>Search</span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_simple_search_form.html.erb
<div class='margin-top-9'>
  <%= form_tag movies_path, method: :get, class: 'form-inline' do %>
    <div class='form-group'>
      <%= text_field_tag :search, params[:search], class:'form-control', placeholder: 'Search Movies Here' %>
    </div>
    <%= button_tag(type: 'submit', class: 'btn btn-primary ') do %>
      <span class='glyphicon glyphicon-search' aria-hidden='true'></span>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Rated</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='black-background'>
    <div class="full-height">
      <%= render 'layouts/header'%>
      <%= render 'layouts/alert'%>

      <div class='container'>
        <%= yield %>
      </div>
      </div>
      <%= render 'layouts/footer'%>
      <div class="clearfix"></div>
    </div>
    <script type="text/javascript">
      $(function() {
        <%= yield :js_init %>
      });
    </script>
  </body>
</html>